services:
  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptime -d uptime"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:17-alpine
    profiles:
      - test

    environment:
      POSTGRES_DB: uptime_test
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime

    ports:
      - "127.0.0.1:5433:5432"

    tmpfs:
      - /var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U uptime -d uptime_test" ]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: