"""create status pages

Revision ID: 4741c9f0a468
Revises: f460d22f6f9c
Create Date: 2026-09-05 18:26:51.423737

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4741c9f0a468"
down_revision: str | Sequence[str] | None = "f460d22f6f9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "status_page_monitors",
        sa.Column("status_page_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["monitor_id"], ["monitors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["status_page_id"], ["status_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("status_page_id", "monitor_id"),
        sa.UniqueConstraint(
            "status_page_id", "monitor_id", name="uq_status_page_monitor"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_page_monitors")
    op.drop_table("status_pages")
    # ### end Alembic commands ###
