"""add outbox delivery state

Revision ID: 63ba83236660
Revises: 7e9bce4f7e2b
Create Date: 2026-09-02 21:08:53.878529

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63ba83236660"
down_revision: str | Sequence[str] | None = "7e9bce4f7e2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "outbox_events",
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_outbox_events_delivery",
        "outbox_events",
        ["processed_at", "next_attempt_at", "locked_until"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_events_delivery", table_name="outbox_events")
    op.drop_column("outbox_events", "locked_until")
    op.drop_column("outbox_events", "next_attempt_at")
    # ### end Alembic commands ###
