"""create outbox events table

Revision ID: 7e9bce4f7e2b
Revises: 5b67aa3761a1
Create Date: 2026-09-02 18:25:34.520854

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9bce4f7e2b"
down_revision: str | Sequence[str] | None = "5b67aa3761a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("incident_opened", "incident_resolved", name="outbox_event_type"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_events_processed_at_created_at",
        "outbox_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_events_processed_at_created_at", table_name="outbox_events"
    )
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
