"""create checks table

Revision ID: 93ef03022add
Revises: 963ab9d4c215
Create Date: 2026-08-30 15:35:54.909459

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93ef03022add"
down_revision: str | Sequence[str] | None = "963ab9d4c215"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("response_time_ms", sa.Float(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["monitor_id"], ["monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_checks_monitor_id_checked_at",
        "checks",
        ["monitor_id", "checked_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_checks_monitor_id_checked_at", table_name="checks")
    op.drop_table("checks")
    # ### end Alembic commands ###
