"""simplify outbox delivery state

Revision ID: f460d22f6f9c
Revises: 398237eeacbc
Create Date: 2026-09-05 16:49:32.866766

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f460d22f6f9c"
down_revision: str | Sequence[str] | None = "398237eeacbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_events_delivery"), table_name="outbox_events")
    op.drop_index(
        op.f("ix_outbox_events_processed_at_created_at"), table_name="outbox_events"
    )
    op.create_index(
        "ix_outbox_events_pending",
        "outbox_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.drop_column("outbox_events", "attempts")
    op.drop_column("outbox_events", "locked_until")
    op.drop_column("outbox_events", "last_error")
    op.drop_column("outbox_events", "next_attempt_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column(
            "next_attempt_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "outbox_events",
        sa.Column(
            "last_error", sa.VARCHAR(length=2000), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "outbox_events",
        sa.Column(
            "locked_until",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "outbox_events",
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events")
    op.create_index(
        op.f("ix_outbox_events_processed_at_created_at"),
        "outbox_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_delivery"),
        "outbox_events",
        ["processed_at", "next_attempt_at", "locked_until"],
        unique=False,
    )
    # ### end Alembic commands ###
